In [1]:
import pandas as pd

In [57]:
qnetwork_sheets = [pd.read_csv("dqn_results/dqn-1hl-2022-03-09 04-34-45.csv"), 
              pd.read_csv("dqn_results/dqn-1hl-2022-03-11 03-55-36.csv"),
              pd.read_csv("dqn_results/dqn-1hl-2022-03-12 21-34-02.csv"),
              pd.read_csv("dqn_results/dqn-1hl-2022-03-12 22-11-56.csv"),
              pd.read_csv("dqn_results/dqn-1hl-2022-03-13 14-11-15.csv"),
              pd.read_csv("dqn_results/dqn-1hl-2022-03-13 20-48-57.csv"),
              pd.read_csv("dqn_results/dqn-1hl-2022-03-13 22-01-26.csv"),
              pd.read_csv("dqn_results/dqn-1hl-2022-03-14 04-07-20.csv"),
              pd.read_csv("dqn_results/dqn-1hl-2022-03-14 04-42-41.csv"),
              pd.read_csv("dqn_results/dqn-1hl-2022-03-14 09-51-58.csv"),
              pd.read_csv("dqn_results/dqn-1hl-2022-03-15 15-24-53.csv"),
              pd.read_csv("dqn_results/dqn-2hl-2022-03-13 16-36-15.csv"),
              pd.read_csv("dqn_results/dqn-2hl-2022-03-15 14-48-33.csv"),
              pd.read_csv("dqn_results/dqn-ani-1hl-2022-03-14 10-49-57.csv"),
              pd.read_csv("dqn_results/dqn-ani-1hl-2022-03-15 11-13-53.csv"),
              pd.read_csv("dqn_results/dqn-ani2-1hl-2022-03-15 20-32-06.csv"),
              pd.read_csv("dqn_results/dqn-ani2-1hl-2022-03-28 19-53-12.csv"),
              pd.read_csv("dqn_results/dqn-gru-2022-03-15 18-46-07.csv"),
              pd.read_csv("dqn_results/rnn-2022-03-13 09-43-17.csv"),
              pd.read_csv("dqn_results/rnn-2022-03-16 13-55-17.csv")]

In [58]:
tab_sheets = [pd.read_csv("tabular_results/best-tabular-2022-03-29 11-26-48.csv"), pd.read_csv("tabular_results/best-tabular-2022-03-29 12-16-21.csv"),
         pd.read_csv("tabular_results/r1-tabular-2022-03-29 12-40-57.csv"), pd.read_csv("tabular_results/r10-tabular-2022-03-29 18-27-35.csv"),
         pd.read_csv("tabular_results/r10-tabular-2022-03-29 21-25-43.csv"), pd.read_csv("tabular_results/r2-tabular-2022-03-29 12-56-07.csv"),
         pd.read_csv("tabular_results/r3-tabular-2022-03-29 13-08-03.csv"), pd.read_csv("tabular_results/r4-tabular-2022-03-29 13-19-47.csv"),
         pd.read_csv("tabular_results/r5-tabular-2022-03-29 13-32-34.csv"), pd.read_csv("tabular_results/r6-tabular-2022-03-29 13-45-12.csv"),
         pd.read_csv("tabular_results/r7-tabular-2022-03-29 13-58-07.csv"), pd.read_csv("tabular_results/r7-tabular-2022-03-29 16-08-52.csv"),
         pd.read_csv("tabular_results/r8-tabular-2022-03-29 14-08-03.csv"), pd.read_csv("tabular_results/tabular-2022-03-20 09-56-38.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-20 11-11-09.csv"), pd.read_csv("tabular_results/tabular-2022-03-23 18-17-10.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-23 18-21-51.csv"), pd.read_csv("tabular_results/tabular-2022-03-23 18-54-08.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-24 03-49-58.csv"), pd.read_csv("tabular_results/tabular-2022-03-24 05-55-35.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-24 06-28-06.csv"), pd.read_csv("tabular_results/tabular-2022-03-24 07-10-42.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-25 15-43-52.csv"), pd.read_csv("tabular_results/tabular-2022-03-26 17-55-19.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-26 19-49-35.csv"), pd.read_csv("tabular_results/tabular-2022-03-26 20-05-45.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-26 20-57-46.csv"), pd.read_csv("tabular_results/tabular-2022-03-26 21-29-27.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-27 07-17-32.csv"), pd.read_csv("tabular_results/tabular-2022-03-27 14-03-17.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-27 16-29-06.csv"), pd.read_csv("tabular_results/tabular-2022-03-27 18-16-18.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-27 18-36-29.csv"), pd.read_csv("tabular_results/tabular-2022-03-27 19-50-44.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-27 21-27-05.csv"), pd.read_csv("tabular_results/tabular-2022-03-27 22-27-42.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-27 23-36-22.csv"), pd.read_csv("tabular_results/tabular-2022-03-28 03-08-38.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-28 19-28-04.csv"), pd.read_csv("tabular_results/tabular-2022-03-28 20-16-44.csv"),
         pd.read_csv("tabular_results/tabular-2022-03-29 12-28-10.csv"), pd.read_csv("tabular_results/tabular-2022-03-30 01-32-53.csv"),]

In [59]:
def clean_up_tabular(df: pd.DataFrame) -> pd.DataFrame:
    df = df.drop(["Unnamed: 0", "model"], axis=1)
    
    return df 

def map_model(x: str) -> str:
    if "GRU" in x:
        return "GRU"
    
    return "RNN" if "RNN" in x else "DQN"

def clean_up_qnetwork(df: pd.DataFrame) -> pd.DataFrame:
    df = df.drop(["Unnamed: 0"], axis=1)
    df["model"] = df["model"].apply(map_model)
    df = df.rename(columns={"model" : "ModelType"})
    
    return df

In [60]:
print("Cleaning Q-Network Sheets")
for idx, qnetwork_sheet in enumerate(qnetwork_sheets):
    qnetwork_sheets[idx] = clean_up_qnetwork(qnetwork_sheet)   
print("Finished cleaning Q-Network")

print("Cleaning tabular")
for idx, tab_sheet in enumerate(tab_sheets):
    tab_sheets[idx] = clean_up_tabular(tab_sheet)   
print("Finished cleaning tabular")

Cleaning Q-Network Sheets
Finished cleaning Q-Network
Cleaning tabular
Finished cleaning tabular

In [63]:
# delete redundant columns
sheets = qnetwork_sheets + tab_sheets

for sheet in sheets:
    if "Model Type" in sheet.columns:
        sheet.drop("Model Type", inplace=True, axis=1)

for sheet in sheets:
    if "Unnamed: 0.1" in sheet.columns:
        sheet.drop("Unnamed: 0.1", inplace=True, axis=1)

In [64]:
columns = []
for idx, sheet in enumerate(sheets):
    for col in sheet.columns:
        if not col in columns:
            print(f"Adding {col} to columns.")
            columns.append(col)

Adding ModelType to columns.
Adding lookback to columns.
Adding n1 to columns.
Adding epsilon to columns.
Adding epsilon_decay to columns.
Adding learning_rate to columns.
Adding discount_rate to columns.
Adding tr_cooperation_percentage to columns.
Adding tr_defection_percentage to columns.
Adding tr_final_loss to columns.
Adding tr_mean_reward to columns.
Adding tr_cumul_reward to columns.
Adding tr_cumul_regret to columns.
Adding tn_rank to columns.
Adding tn_mean_score to columns.
Adding tn_mean_time to columns.
Adding agents to columns.
Adding n2 to columns.
Adding hidden_size to columns.
Adding num_layers to columns.
Adding decay_limit to columns.

In [65]:
# now we join the spreadsheets together

# first we need to make sure all sheets have the same columns
for sheet in sheets:
    for col in columns:
        if not col in sheet.columns:
            sheet[col] = None

In [66]:
master_sheet = pd.concat(sheets, ignore_index=True, sort=True)

In [67]:
master_sheet

,ModelType,agents,decay_limit,discount_rate,epsilon,epsilon_decay,hidden_size,learning_rate,lookback,n1,...,num_layers,tn_mean_score,tn_mean_time,tn_rank,tr_cooperation_percentage,tr_cumul_regret,tr_cumul_reward,tr_defection_percentage,tr_final_loss,tr_mean_reward
0,DQN,"TitForTat,OmegaTFT",NaN,0.95,0.2,0.0,None,0.001,2.0,4,...,None,609.140323,18.849598,25.0,0.412525,57390.0,62610.0,0.587475,1.116258,1.565250
1,DQN,"TitForTat,OmegaTFT",NaN,0.95,0.2,0.0,None,0.001,2.0,8,...,None,646.303226,21.482931,25.0,0.878275,11181.0,108819.0,0.121725,2.247977,2.720475
2,DQN,"TitForTat,OmegaTFT",NaN,0.95,0.2,0.0,None,0.001,2.0,12,...,None,539.161290,18.026233,25.0,0.407200,66691.0,53309.0,0.592800,0.438530,1.332725
3,DQN,"TitForTat,OmegaTFT",NaN,0.95,0.2,0.0,None,0.001,2.0,16,...,None,546.259677,31.196609,25.0,0.453475,55424.0,64576.0,0.546525,1.167565,1.614400
4,DQN,"TitForTat,OmegaTFT",NaN,0.95,0.2,0.0,None,0.001,2.0,24,...,None,534.727419,18.156603,25.0,0.568300,52790.0,67210.0,0.431700,1.256334,1.680250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4330,None,Borufsen,0.05,0.99,0.1,0.0,None,0.100,10.0,None,...,None,722.812581,4.406982,24.0,0.908120,221732.0,5778268.0,0.091880,NaN,2.889134
4331,None,Borufsen,0.05,0.95,0.2,0.0,None,0.010,10.0,None,...,None,715.381613,4.206030,25.0,0.627424,1496352.0,4503648.0,0.372576,NaN,2.251824
4332,None,Borufsen,0.05,0.99,0.2,0.0,None,0.010,10.0,None,...,None,434.066129,30.187939,30.0,0.602185,1732151.0,4267849.0,0.397815,NaN,2.133925
4333,None,Borufsen,0.05,0.95,0.2,0.0,None,0.100,10.0,None,...,None,709.700968,4.100973,25.0,0.730523,1134159.0,4865841.0,0.269477,NaN,2.432920
4334,None,Borufsen,0.05,0.99,0.2,0.0,None,0.100,10.0,None,...,None,458.034194,29.071106,27.0,0.725463,1002916.0,4997084.0,0.274537,NaN,2.498542

In [68]:
master_sheet.to_csv("masterspreadsheet_all.csv")